app:
  name: nlxiaoy-blog
  version: 1.0.0

log:
  level: debug

http:
  port: 8080
  use_prefork_mode: false

mysql:
  host: 123.207.71.97
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  dbname: blog_db2
  username: root
  password: "000819"
  time_zone: Asia/Shanghai
  max_idle_conns: 10
  max_open_conns: 100
  sslmode: disable

redis:
  host: 123.207.71.97
  port: 6379
  password: "000819"
  db: 2

minio:
  endpoint: 123.207.71.97:9000
  access_key: admin
  secret_key: 19981206Xzz
  use_ssl: false
  bucket: bolg-file
  region: ""

captcha:
  height: 80
  width: 240
  length: 6
  max_skew: 0.7
  dot_count: 80

smtp:
  host: smtp.163.com
  port: 465
  username: 猪猪窝杂谈
  password: DNcyMUZ6WhWPsyXv
  from: nlxiaoys@163.com

jwt:
  access_secret: pQCUt3LWXuHYCQcwUbSa0cWuaGdjFdSye80POpBqbVA
  refresh_secret: W_iF_yLMkZuJuH_rFs7PC9nweXIRprSz2hMWr_1zGU8i6JC8NCF06mSs0zngqe8lgBjhcy0hqE7P5ipQmQ84ag
  access_ttl: 15m
  refresh_ttl: 168h
  issuer: nimbus-blog

twofa:
  qr_width: 200
  qr_height: 200
  encryption_key: rgITfrGu8c7zeHB6WcGVdH7MZRgtE+516HlK0BQlSH0=

openai:
  api_key: sk-24e49f26a7114bfd9bd9ab3010a686fd
  base_url: https://api.deepseek.com
  model: deepseek-chat

swagger:
  enabled: false
